.TH mount.ofs 8 "April 5, 2011" "version 0.2.3" ""
.SH NAME
mount.ofs \- mount an Offline File System
.SH SYNOPSIS
.B mount.ofs
.I remotetarget dir
.B [\-o
.I options
.B ]
.PP
.B mount.ofs [\-Vh] 
.SH DESCRIPTION
.B mount.ofs
is meant to be used by the
.BR mount (8)
command for mounting Offline File Systems. This subcommand, however, can
also be used as a standalone command with limited functionality.
.SH OPTIONS
.TP
.B \-V
Print version.
.TP
.B \-h
Print help message.
.TP
.B ofsoptions
Options passed on to the
.BR mount (8)
command that mounts the remote file system
.I remotetarget
.SH FILES
.I /etc/fstab
file system table
.PP
.I /etc/mtab
table of mounted file systems
.PP
.I /etc/ofs.conf
ofs configuration file
.SH AUTHOR
Peter Trommler <peter.trommler@ohm-hochschule.de>
.SH SEE ALSO
.BR mount (8)
.SH BUGS
Currently
.B mount.ofs
runs with the uid and gid of the calling
.B mount
command, and all file operations on the remote file system will be carried out using these
ids. NFS access will only work if
.B mount.ofs
is run with the user's uid and gid. Multiple simultaneous users are not supported.
.SH CREDITS
Most of this manual page has been borrowed from the Linux
.BR mount.nfs (8)
manual page by Amid Gud.  